import "../../styles/settings/globals.css";
import "../../styles/settings/variables.css";

export const metadata = {
  title: "MyWiki",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
